### ISSUE TITLE
server crashes

### ISSUE THREAD

**Issue by triniwiz** [buddycloud/buddycloud-http-api#200]
i tired the git and the deb only the git version seem a bit stable with the deb the server crashes just by opening the webclient

the error i just before it crashes

error: uncaughtException: Object [object Object] has no method 'setCache' date=Thu Mar 12 2015 13:33:32 GMT-0400 (EDT), pid=6914, uid=0, gid=0, cwd=/opt/buddycloud-http-api, execPath=/usr/bin/nodejs, version=v0.10.25, argv=[node, /opt/buddycloud-http-api/server.js], rss=67543040, heapTotal=56160000, heapUsed=19672400, loadavg=[0.0029296875, 0.0146484375, 0.1875], uptime=4103.206516203, trace=[column=20, file=/opt/buddycloud-http-api/src/websocket.js, function=, line=29, method=null, native=false, column=33, file=/opt/buddycloud-http-api/node_modules/primus/node_modules/eventemitter3/index.js, function=Primus.emit, line=93, method=emit, native=false, column=12, file=/opt/buddycloud-http-api/node_modules/primus/spark.js, function=tick, line=275, method=null, native=false, column=13, file=node.js, function=process._tickCallback, line=415, method=_tickCallback, native=false], stack=[TypeError: Object [object Object] has no method 'setCache',     at Primus.<anonymous> (/opt/buddycloud-http-api/src/websocket.js:29:20),     at Primus.emit (/opt/buddycloud-http-api/node_modules/primus/node_modules/eventemitter3/index.js:93:33),     at tick (/opt/buddycloud-http-api/node_modules/primus/spark.js:275:12),     at process._tickCallback (node.js:415:13)]

i'm using nginx

**Comment by imaginator** [comment]
similar to https://github.com/buddycloud/buddycloud-http-api/issues/203
