### ISSUE TITLE
restarting continuously when websocket-y bits used.

### ISSUE THREAD

**Issue by imaginator** [buddycloud/buddycloud-http-api#203]
Log is showing: 

```
2015-07-14T12:59:42.390Z - error:
2015-07-14T12:59:43.209Z - debug: Server started with configuration profile "production"
2015-07-14T12:59:43.210Z - debug: Listening on port 9123
2015-07-14T12:59:46.235Z - debug: Websocket connection made
2015-07-14T12:59:46.239Z - error: uncaughtException: Object [object Object] has no method 'setCache' date=Tue Jul 14 2015 12:59:46 GMT+0000 (UTC), pid=8, uid=0, gid=0, cwd=/usr/share/buddycloud-http-api, execPath=/usr/bin/nodejs, version=v0.10.37, argv=[node, /usr/share/buddycloud-http-api/server.js], rss=47927296, heapTotal=53076224, heapUsed=22266832, loadavg=[0.65576171875, 0.36181640625, 0.3203125], uptime=530987.899803369, trace=[column=20, file=/usr/share/buddycloud-http-api/src/websocket.js, function=, line=29, method=null, native=false, column=33, file=/usr/share/buddycloud-http-api/node_modules/primus/node_modules/eventemitter3/index.js, function=Primus.emit, line=93, method=emit, native=false, column=12, file=/usr/share/buddycloud-http-api/node_modules/primus/spark.js, function=tick, line=275, method=null, native=false, column=13, file=node.js, function=process._tickCallback, line=448, method=_tickCallback, native=false], stack=[TypeError: Object [object Object] has no method 'setCache',     at Primus.<anonymous> (/usr/share/buddycloud-http-api/src/websocket.js:29:20),     at Primus.emit (/usr/share/buddycloud-http-api/node_modules/primus/node_modules/eventemitter3/index.js:93:33),     at tick (/usr/share/buddycloud-http-api/node_modules/primus/spark.js:275:12),     at process._tickCallback (node.js:448:13)]
2015-07-14T12:59:46.240Z - error: uncaughtException: Object [object Object] has no method 'setCache' date=Tue Jul 14 2015 12:59:46 GMT+0000 (UTC), pid=8, uid=0, gid=0, cwd=/usr/share/buddycloud-http-api, execPath=/usr/bin/nodejs, version=v0.10.37, argv=[node, /usr/share/buddycloud-http-api/server.js], rss=48005120, heapTotal=54096128, heapUsed=22740264, loadavg=[0.65576171875, 0.36181640625, 0.3203125], uptime=530987.903332377, trace=[column=20, file=/usr/share/buddycloud-http-api/src/websocket.js, function=, line=29, method=null, native=false, column=33, file=/usr/share/buddycloud-http-api/node_modules/primus/node_modules/eventemitter3/index.js, function=Primus.emit, line=93, method=emit, native=false, column=12, file=/usr/share/buddycloud-http-api/node_modules/primus/spark.js, function=tick, line=275, method=null, native=false, column=13, file=node.js, function=process._tickCallback, line=448, method=_tickCallback, native=false], stack=[TypeError: Object [object Object] has no method 'setCache',     at Primus.<anonymous> (/usr/share/buddycloud-http-api/src/websocket.js:29:20),     at Primus.emit (/usr/share/buddycloud-http-api/node_modules/primus/node_modules/eventemitter3/index.js:93:33),     at tick (/usr/share/buddycloud-http-api/node_modules/primus/spark.js:275:12),     at process._tickCallback (node.js:448:13)]
2015-07-14T12:59:46.240Z - error: uncaughtException: Object [object Object] has no method 'setCache' date=Tue Jul 14 2015 12:59:46 GMT+0000 (UTC), pid=8, uid=0, gid=0, cwd=/usr/share/buddycloud-http-api, execPath=/usr/bin/nodejs, version=v0.10.37, argv=[node, /usr/share/buddycloud-http-api/server.js], rss=48005120, heapTotal=54096128, heapUsed=22821048, loadavg=[0.65576171875, 0.36181640625, 0.3203125], uptime=530987.903801347, trace=[column=20, file=/usr/share/buddycloud-http-api/src/websocket.js, function=, line=29, method=null, native=false, column=33, file=/usr/share/buddycloud-http-api/node_modules/primus/node_modules/eventemitter3/index.js, function=Primus.emit, line=93, method=emit, native=false, column=12, file=/usr/share/buddycloud-http-api/node_modules/primus/spark.js, function=tick, line=275, method=null, native=false, column=13, file=node.js, function=process._tickCallback, line=448, method=_tickCallback, native=false], stack=[TypeError: Object [object Object] has no method 'setCache',     at Primus.<anonymous> (/usr/share/buddycloud-http-api/src/websocket.js:29:20),     at Primus.emit (/usr/share/buddycloud-http-api/node_modules/primus/node_modules/eventemitter3/index.js:93:33),     at tick (/usr/share/buddycloud-http-api/node_modules/primus/spark.js:275:12),     at process._tickCallback (node.js:448:13)]
2015-07-14T12:59:46.241Z - error:
2015-07-14T12:59:47.002Z - debug: Server started with configuration profile "production"
```

**Comment by lloydwatkin** [comment]
You need to bump the versions of `xmpp-ftw`/`xmpp-ftw-buddycloud` in use. Caching was added later and is used to speed up discovery of various components when users are coming from/querying the same domains.

**Comment by imaginator** [comment]
Fixed with the newer version. Thanks!
